
backend:
  name: github
  repo: sgithuku/charmi-blog

media_folder: blog/images
public_folder: blog/images

collections:
  - name: blog
    label: Blog posts
    folder: blog
    create: true
    fields:
      - { name: date, label: Date, widget: date }
      - { name: title, label: Title }
      - { name: cover, label: Cover, widget: image }
      - { name: body, label: Body, widget: markdown }

